### ISSUE TITLE
auto_batch runAutoBatch.py issue

### ISSUE THREAD

**Issue by chris-wood** [JHUISI/auto-tools#1]
What version of Charm does auto_batch require? I downloaded and installed v0.43 for python3, yet I receive the following missing module error when trying to run runAutoBatch.py:

$ python3 runAutoBatch.py
Traceback (most recent call last):
  File "runAutoBatch.py", line 4, in <module>
    from batcher import batchverify
  File "/home/caw/Projects/auto-tools/auto_batch/batcher/batchverify.py", line 8, in <module>
    from batcher.batchtechniques import *
  File "/home/caw/Projects/auto-tools/auto_batch/batcher/batchtechniques.py", line 2, in <module>
    from batcher.batchlang import *
  File "/home/caw/Projects/auto-tools/auto_batch/batcher/batchlang.py", line 24, in <module>
    from charm.toolbox.enum import *
  File "/usr/local/lib/python3.4/dist-packages/charm/**init**.py", line 5, in <module>
    import charm.core.benchmark 
ImportError: No module named 'charm.core.benchmark

**Comment by jakinyele** [comment]
Hmm, that should've worked. All we really need is the 'enum' support which is really independent of Charm. I'll commit a fix asap. Thanks!
